// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/repository.go -destination=mock/mock_repository.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockBasicChatRepository is a mock of BasicChatRepository interface.
type MockBasicChatRepository struct {
	ctrl     *gomock.Controller
	recorder *MockBasicChatRepositoryMockRecorder
	isgomock struct{}
}

// MockBasicChatRepositoryMockRecorder is the mock recorder for MockBasicChatRepository.
type MockBasicChatRepositoryMockRecorder struct {
	mock *MockBasicChatRepository
}

// NewMockBasicChatRepository creates a new mock instance.
func NewMockBasicChatRepository(ctrl *gomock.Controller) *MockBasicChatRepository {
	mock := &MockBasicChatRepository{ctrl: ctrl}
	mock.recorder = &MockBasicChatRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBasicChatRepository) EXPECT() *MockBasicChatRepositoryMockRecorder {
	return m.recorder
}

// AskBasicBranchChat mocks base method.
func (m *MockBasicChatRepository) AskBasicBranchChat(ctx context.Context, msg string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AskBasicBranchChat", ctx, msg)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AskBasicBranchChat indicates an expected call of AskBasicBranchChat.
func (mr *MockBasicChatRepositoryMockRecorder) AskBasicBranchChat(ctx, msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AskBasicBranchChat", reflect.TypeOf((*MockBasicChatRepository)(nil).AskBasicBranchChat), ctx, msg)
}

// AskBasicChat mocks base method.
func (m *MockBasicChatRepository) AskBasicChat(ctx context.Context, msg string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AskBasicChat", ctx, msg)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AskBasicChat indicates an expected call of AskBasicChat.
func (mr *MockBasicChatRepositoryMockRecorder) AskBasicChat(ctx, msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AskBasicChat", reflect.TypeOf((*MockBasicChatRepository)(nil).AskBasicChat), ctx, msg)
}

// AskBasicParallelChat mocks base method.
func (m *MockBasicChatRepository) AskBasicParallelChat(ctx context.Context, msg string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AskBasicParallelChat", ctx, msg)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AskBasicParallelChat indicates an expected call of AskBasicParallelChat.
func (mr *MockBasicChatRepositoryMockRecorder) AskBasicParallelChat(ctx, msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AskBasicParallelChat", reflect.TypeOf((*MockBasicChatRepository)(nil).AskBasicParallelChat), ctx, msg)
}

// AskBasicPromptTemplateChat mocks base method.
func (m *MockBasicChatRepository) AskBasicPromptTemplateChat(ctx context.Context, msg string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AskBasicPromptTemplateChat", ctx, msg)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AskBasicPromptTemplateChat indicates an expected call of AskBasicPromptTemplateChat.
func (mr *MockBasicChatRepositoryMockRecorder) AskBasicPromptTemplateChat(ctx, msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AskBasicPromptTemplateChat", reflect.TypeOf((*MockBasicChatRepository)(nil).AskBasicPromptTemplateChat), ctx, msg)
}

// AskWithGraph mocks base method.
func (m *MockBasicChatRepository) AskWithGraph(ctx context.Context, msg string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AskWithGraph", ctx, msg)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AskWithGraph indicates an expected call of AskWithGraph.
func (mr *MockBasicChatRepositoryMockRecorder) AskWithGraph(ctx, msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AskWithGraph", reflect.TypeOf((*MockBasicChatRepository)(nil).AskWithGraph), ctx, msg)
}

// AskWithGraphWithBranch mocks base method.
func (m *MockBasicChatRepository) AskWithGraphWithBranch(ctx context.Context, arg1 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AskWithGraphWithBranch", ctx, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AskWithGraphWithBranch indicates an expected call of AskWithGraphWithBranch.
func (mr *MockBasicChatRepositoryMockRecorder) AskWithGraphWithBranch(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AskWithGraphWithBranch", reflect.TypeOf((*MockBasicChatRepository)(nil).AskWithGraphWithBranch), ctx, arg1)
}

// AskWithTool mocks base method.
func (m *MockBasicChatRepository) AskWithTool(ctx context.Context, msg string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AskWithTool", ctx, msg)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AskWithTool indicates an expected call of AskWithTool.
func (mr *MockBasicChatRepositoryMockRecorder) AskWithTool(ctx, msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AskWithTool", reflect.TypeOf((*MockBasicChatRepository)(nil).AskWithTool), ctx, msg)
}
