// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/service.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/service.go -destination=mock/mock_service.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockBasicChatService is a mock of BasicChatService interface.
type MockBasicChatService struct {
	ctrl     *gomock.Controller
	recorder *MockBasicChatServiceMockRecorder
	isgomock struct{}
}

// MockBasicChatServiceMockRecorder is the mock recorder for MockBasicChatService.
type MockBasicChatServiceMockRecorder struct {
	mock *MockBasicChatService
}

// NewMockBasicChatService creates a new mock instance.
func NewMockBasicChatService(ctrl *gomock.Controller) *MockBasicChatService {
	mock := &MockBasicChatService{ctrl: ctrl}
	mock.recorder = &MockBasicChatServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBasicChatService) EXPECT() *MockBasicChatServiceMockRecorder {
	return m.recorder
}

// AskBasicChat mocks base method.
func (m *MockBasicChatService) AskBasicChat(ctx context.Context, msg string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AskBasicChat", ctx, msg)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AskBasicChat indicates an expected call of AskBasicChat.
func (mr *MockBasicChatServiceMockRecorder) AskBasicChat(ctx, msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AskBasicChat", reflect.TypeOf((*MockBasicChatService)(nil).AskBasicChat), ctx, msg)
}

// AskBasicPromptTemplateChat mocks base method.
func (m *MockBasicChatService) AskBasicPromptTemplateChat(ctx context.Context, msg string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AskBasicPromptTemplateChat", ctx, msg)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AskBasicPromptTemplateChat indicates an expected call of AskBasicPromptTemplateChat.
func (mr *MockBasicChatServiceMockRecorder) AskBasicPromptTemplateChat(ctx, msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AskBasicPromptTemplateChat", reflect.TypeOf((*MockBasicChatService)(nil).AskBasicPromptTemplateChat), ctx, msg)
}
